language: c
os: linux
compiler: gcc
sudo: false

deploy:
  local-dir: formulae.brew.sh
  repo: Homebrew/formulae.brew.sh
  target-branch: master
  verbose: true
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    all_branches: true

before_install:
  - HOMEBREW_REPOSITORY="$HOME/Homebrew"
  - export PATH="$HOMEBREW_REPOSITORY/bin:$PATH"
  # umask 022 fixes Linux `brew tests` failures
  - umask 022
  - chmod 644 Formula/*.rb
  - rm -rf $HOMEBREW_REPOSITORY
  - travis_retry git clone --depth=1 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  # trigger vendored ruby installation
  - brew help

before_script:
  - travis_retry git clone https://$GITHUB_TOKEN@github.com/Homebrew/formulae.brew.sh
  - openssl aes-256-cbc -K $encrypted_973277d8afbb_key -iv $encrypted_973277d8afbb_iv -in formulae.brew.sh/.homebrew_analytics.json.enc -out formulae.brew.sh/.homebrew_analytics.json -d


script:
  - cd formulae.brew.sh && rake
